import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ChildrenType from "@/types/children";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
